baseURL = "https://bibymaths.github.io"
uglyURLs = false
languageCode = "en-us"
title = ""
theme = "PaperMod"
copyright = "2025 © Abhinav Mishra"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  env = "production"
  title = ""
  description = "Bioinformatician who loves mathematics"
  keywords = ["Bioinformatics", "Mathematics", "Abhinav Mishra"]
  defaultTheme = "auto"
  ShowBreadCrumbs = true
  ShowReadingTime = false
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  ShowShareButtons = true
  ShowWordCount = false
  hideFooter = false
  UseHugoToc = false

[params.profileMode]
  enabled = true
  subtitle = "<p style='font-size:1.35rem; font-weight:700; line-height:1.4; margin:0;'>Computational Biologist • Data & Software • Open Science</p>"
  imageUrl = "photo.png"
  imageTitle = ""
  imageWidth = 250
  imageHeight = 250
  buttons = [
    { name = "Impressum", url = "/impressum/" }
  ]

[params.assets]
  customCSS = ["css/extended/custom.css"]
  favicon = "/files/favicon.ico"
  favicon16 = "/files/logo_16x16.png"
  favicon32 = "/files/logo_32x32.png"
  apple_touch_icon = "/files/logo_128x128.png"
  safari_pinned_tab = "/files/logo.svg"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/bibymaths"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/bibymaths"

[[params.socialIcons]]
  name = "x"
  url = "https://x.com/shadytoyou"

[[params.socialIcons]]
  name = "email"
  url = "mailto:mishraabhinav36@gmail.com"

[[params.author]]
  name = "Abhinav Mishra"
  email = "mishraabhinav36@gmail.com"

[menu]

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 3

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4

  [[menu.main]]
    name = "Presentations & Posters"
    url = "/presentations/"
    weight = 5

#  [[menu.main]]
#    name = "Posts"
#    url = "/posts/"
#    weight = 6

  [[menu.main]]
    name = "Photography"
    url = "/gallery/"
    weight = 7

#  [[menu.main]]
#    name = "BioBaes"
#    url = "/biobaes/"
#    weight = 8